---

- name: Install required packages for apt repository plugin in Debian
  apt:
    name: augeas-tools
    state: present

- name: Create bundle destination directory
  file:
    path: '{{ nexus_installation_dir }}/nexus-{{ nexus_version }}/system/net/staticsnow/nexus-repository-apt/{{ nexus_apt_repository_version }}'
    state: directory
    owner: nexus
    group: nexus
    mode: 0755

- name: Copy plugin bundle to nexus
  copy:
    src: 'nexus-repository-apt-{{ nexus_apt_repository_version }}.jar'
    dest: '{{ nexus_installation_dir }}/nexus-{{ nexus_version }}/system/net/staticsnow/nexus-repository-apt/{{ nexus_apt_repository_version }}/nexus-repository-apt-{{ nexus_apt_repository_version }}.jar'

- name: Copy template script to load bundle
  template:
    src: add_apt_repository.aug.j2
    dest: /tmp/add_apt_repository.aug
    mode: 0755

- name: Load apt repostory bundle in Nexus
  become: yes
  command: /tmp/add_apt_repository.aug
  notify:
    - nexus-service-restart
    - wait-for-nexus
    - wait-for-nexus-port
